# -*- coding: utf-8 -*-
"""16/10/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLx1NDe-cL9-KOqpYhUNvI9nEPtJaCDX
"""

amazon_website = [("watch", 5000), ("phone", 10000), ("laptop", 50000), ("shirt", 1000)]
choice = (input("Enter the product you want to buy: ")).lower()
quantity = int(input("Enter the quantity: "))
total_price = 0
for item in  amazon_website:
  if item[0] == choice:
    total_price = total_price + (int(item[1]))*quantity
    break
else:
  print("Out of stock")
print(f"Total Bill of the Product {choice} for {quantity} no of quantity is: {total_price}")